# Generated by Django 3.2.17 on 2023-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('عظام', 'عظام'), ('جلديه', 'جلديه'), ('أسنان', 'أسنان'), ('مخ واعصاب', 'مخ واعصاب')], max_length=50, null=True, verbose_name=' دكتور؟:'),
        ),
    ]
